language: scala

scala:
  - 2.11.11

services:
  - postgresql

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.ivy2/local
    - $HOME/.sbt/boot

env:
  global:
    - CPPCHECK_VERSION="1.81"
    - SCRIPTS_DIR="/tmp/AnalyzeGithubUsers"
    - secure: "qtZXijaJRhiMU6UEx8eG/gAe4MgGfhqP7+m5adT82RVUKl4bc7KRf5M71zxJbIHr089UN//B5XzIlIs/8i3UOQ4OvgmVHHg2K3IATSC6SThSdpmF0SkeyxzeAcYOgFq+GMXh3IFmVzygpZly+o0JKydeRBf7+cI20ha3De/tsN1vNhUn+R4/Mq1bew/uLWrJ2XvSMoZDqgi9UmYt3pO1NQYvCAHohSdowT6R65EY6CZHSXVLgC6y0LzWme/rhf5y8mhJzRWU6h8GyAVlarfFev371evc/fgsTp7oklnJl81O27IWbsjhTpgBexinpOjUPE4bs0gHQq8ucsJxf4poYlonP/QVeCh6tk+XPdHb+TfbUrR7u3fADrL83vRMvQJirqJVDY/ZNqYdEQq5CveywkPtztalIp3frqFSDWkRTTHXIvTLuPQXr8u05vyhro5BWvO3x+2Kf07ah3pcyUNbBPncSs7K47ux0tid9qV9eFemyiAOu1JfdSMJzB57Pa30oXHdCwv2XvICnQHriQBYOQsR/2sfceA66kQbU8Ri2mzGLHzH4AI5GZvI0pvCpBpdAtndDzp3evHzRrMu7vKVB5JZ2D+eIF1ee3cp9Pxly3SX2lsDVRhfnnnLGvXn9QoAocEX5QvmDlzO5uwv7pZIDViQ+zTYf4jX0M6vpVUr3vQ="

before_script:
  - cp -av analysis/scripts "${SCRIPTS_DIR}" && ls -al "${SCRIPTS_DIR}" && mkdir -p "${SCRIPTS_DIR}/data" && chmod 1777 "${SCRIPTS_DIR}/data"
  - wget --no-verbose "http://github.com/danmar/cppcheck/releases/download/${CPPCHECK_VERSION}/cppcheck-${CPPCHECK_VERSION}.tar.gz" && tar xzvf "cppcheck-${CPPCHECK_VERSION}.tar.gz" && pushd "cppcheck-${CPPCHECK_VERSION}" && g++ -o cppcheck -std=c++0x -include lib/cxx11emu.h -Iexternals/simplecpp -Iexternals/tinyxml -Ilib cli/*.cpp lib/*.cpp externals/simplecpp/simplecpp.cpp externals/tinyxml/*.cpp && mv cppcheck "${SCRIPTS_DIR}/cppcheck" && mv cfg "${SCRIPTS_DIR}/cfg" && chmod o+rx "${SCRIPTS_DIR}/cfg" && ls -ld "${SCRIPTS_DIR}/cfg" ; popd
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe multiverse" && sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe multiverse" && curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash ; sudo apt-get update -qq
  - sudo apt-get install -y nodejs firejail jq ; export PATH="${PATH}:${HOME}/node_modules/.bin:${SCRIPTS_DIR}"
  - pushd "${SCRIPTS_DIR}" && npm install eslint eslint-plugin-better eslint-plugin-mocha eslint-plugin-private-props eslint-plugin-promise decomment && popd
  - sudo /etc/init.d/postgresql stop ; sudo /etc/init.d/postgresql start 9.6 ; analysis/prepare_test_env.sh
  - if ! (find "${HOME}/.ivy2/cache" -type f -name 'ivy-3.1.x-serialization-workaround.xml' | grep scalatest) >> /dev/null ; then git clone https://github.com/alopatindev/scalatest.git && pushd scalatest && git checkout serialization-workaround && sbt ++$TRAVIS_SCALA_VERSION package ; sbt ++$TRAVIS_SCALA_VERSION publishLocal && popd ; fi

script:
  - cppcheck --version ; firejail --version ; python3 --version ; node --version ; jq --version
  - mv analysis/src/main/resources/application.conf.example analysis/src/main/resources/application.conf && sed -i "s!INSERT_YOUR_GITHUB_TOKEN_HERE!${GITHUB_TOKEN}!" analysis/src/main/resources/application.conf
  - sed -i 's!log4j\.rootCategory=.*, console!log4j.rootCategory=ERROR, console!' analysis/src/main/resources/log4j.properties
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle test:scalastyle ; sbt ++$TRAVIS_SCALA_VERSION coverageOn test slow:test coverageReport coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
